### ISSUE TITLE
Module build failed: TypeError: Cannot read property 'contents' of undefined

### ISSUE THREAD

**Issue by z-ZYS-s** [vusion/svg-classic-sprite-loader#1]
```
ERROR in /Users/yusen/Projects/GitHub/Vusion/vusion-cli/node_modules/vusion-css-loader?{"minimize":true,"localIdentName":"[hash:base64:16]","importLoaders":5,"modules":true}!/Users/yusen/Projects/GitHub/Vusion/vusion-cli/node_modules/css-sprite-loader!/Users/yusen/Projects/GitHub/Vusion/vusion-cli/node_modules/svg-classic-sprite-loader!/Users/yusen/Projects/GitHub/Vusion/vusion-cli/node_modules/icon-font-loader!/Users/yusen/Projects/GitHub/Vusion/vusion-cli/node_modules/vusion-vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-4c8beeaf","scoped":false,"hasInlineConfig":true}!/Users/yusen/Projects/GitHub/Vusion/vusion-cli/lib/loaders/import-global-loader.js!/Users/yusen/Projects/GitHub/Vusion/vusion-cli/node_modules/vusion-vue-loader/lib/selector.js?type=styles&index=0!./index.vue
Module build failed: TypeError: Cannot read property 'contents' of undefined
    at Array.spriter.compile (/Users/yusen/Projects/GitHub/Vusion/vusion-cli/node_modules/svg-classic-sprite-loader/lib/svg.js:62:40)
    at /Users/yusen/Projects/GitHub/Vusion/vusion-cli/node_modules/svg-sprite/lib/svg-sprite.js:280:12
    at /Users/yusen/Projects/GitHub/Vusion/vusion-cli/node_modules/svg-sprite/lib/svg-sprite.js:323:3
    at /Users/yusen/Projects/GitHub/Vusion/vusion-cli/node_modules/async/dist/async.js:3874:9
    at /Users/yusen/Projects/GitHub/Vusion/vusion-cli/node_modules/async/dist/async.js:473:16
    at replenish (/Users/yusen/Projects/GitHub/Vusion/vusion-cli/node_modules/async/dist/async.js:993:25)
    at iterateeCallback (/Users/yusen/Projects/GitHub/Vusion/vusion-cli/node_modules/async/dist/async.js:983:17)
    at /Users/yusen/Projects/GitHub/Vusion/vusion-cli/node_modules/async/dist/async.js:958:16
    at /Users/yusen/Projects/GitHub/Vusion/vusion-cli/node_modules/async/dist/async.js:3871:13
    at SVGSpriteCss.SVGSpriteBase._buildHTMLExample (/Users/yusen/Projects/GitHub/Vusion/vusion-cli/node_modules/svg-sprite/lib/svg-sprite/mode/base.js:205:2)
    at SVGSpriteCss.<anonymous> (/Users/yusen/Projects/GitHub/Vusion/vusion-cli/node_modules/svg-sprite/lib/svg-sprite/mode/css.js:121:9)
    at /Users/yusen/Projects/GitHub/Vusion/vusion-cli/node_modules/async/dist/async.js:3874:9
    at /Users/yusen/Projects/GitHub/Vusion/vusion-cli/node_modules/async/dist/async.js:473:16
    at replenish (/Users/yusen/Projects/GitHub/Vusion/vusion-cli/node_modules/async/dist/async.js:993:25)
    at iterateeCallback (/Users/yusen/Projects/GitHub/Vusion/vusion-cli/node_modules/async/dist/async.js:983:17)
    at /Users/yusen/Projects/GitHub/Vusion/vusion-cli/node_modules/async/dist/async.js:958:16
 @ /Users/yusen/Projects/GitHub/Vusion/vusion-cli/node_modules/extract-text-webpack-plugin/dist/loader.js?{"omit":1,"remove":true}!/Users/yusen/Projects/GitHub/Vusion/vusion-cli/node_modules/vue-style-loader!/Users/yusen/Projects/GitHub/Vusion/vusion-cli/node_modules/vusion-css-loader?{"minimize":true,"localIdentName":"[hash:base64:16]","importLoaders":5,"modules":true}!/Users/yusen/Projects/GitHub/Vusion/vusion-cli/node_modules/css-sprite-loader!/Users/yusen/Projects/GitHub/Vusion/vusion-cli/node_modules/svg-classic-sprite-loader!/Users/yusen/Projects/GitHub/Vusion/vusion-cli/node_modules/icon-font-loader!/Users/yusen/Projects/GitHub/Vusion/vusion-cli/node_modules/vusion-vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-4c8beeaf","scoped":false,"hasInlineConfig":true}!/Users/yusen/Projects/GitHub/Vusion/vusion-cli/lib/loaders/import-global-loader.js!/Users/yusen/Projects/GitHub/Vusion/vusion-cli/node_modules/vusion-vue-loader/lib/selector.js?type=styles&index=0!./index.vue 4:14-611
 @ ./index.vue
 @ ./index.js
```

**Comment by z-ZYS-s** [comment]
添加了一个xxx.png?sprite，结果报错了，正则中没有判断是不是.svg文件。

改成这样就好了：
``` js
/background:\s*url\((["']?)(.+?)\.svg(.+?)["']?\)\s*;/g
```
